/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 headphone.gltf 
Author: gorzi (https://sketchfab.com/gorzi90)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/headphones-743c3ae8690f4a07bb3a0cbff52bc5ab
Title: Headphones
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Headphone(props) {
  const { nodes, materials } = useGLTF('/headphone.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.50}>
      <group position={[1.229, 4.492, -0.01]}>
        <mesh geometry={nodes.Object_14.geometry} material={materials.plastik_mat} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.plastik_polysk} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.skorka} />
      </group>
      <group position={[1.559, 4.987, -0.01]}>
        <mesh geometry={nodes.Object_20.geometry} material={materials.plastik_polysk} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.chrom} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.plastik_mat} />
      </group>
      <group position={[-1.211, 3.842, -0.012]}>
        <mesh geometry={nodes.Object_26.geometry} material={materials.chrom} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.guma} />
      </group>
      <group position={[-1.519, 4.987, -0.01]}>
        <mesh geometry={nodes.Object_31.geometry} material={materials.plastik_polysk} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.chrom} />
      </group>
      <group position={[-1.188, 4.492, -0.01]}>
        <mesh geometry={nodes.Object_36.geometry} material={materials.plastik_mat} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.plastik_polysk} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.skorka} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.plastik_mat} position={[0.019, 7.362, -0.165]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.005']} position={[0.945, 4.635, -0.01]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.005']} position={[-0.916, 4.641, -0.01]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.skorka} position={[0.019, 7.259, -0.01]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.plastik_mat} position={[0.019, 7.362, 0.143]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.plastik_mat} position={[1.445, 4.425, -0.01]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.chrom} position={[1.276, 3.924, -0.012]} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.chrom} position={[-1.233, 3.924, -0.012]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.plastik_mat} position={[-1.403, 4.425, -0.01]} />
    </group>
    </group>
  )
}

useGLTF.preload('/headphone.gltf')
