/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 watch.gltf 
Author: polyman (https://sketchfab.com/Polyman_3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-watch-ultra-2-f33263c457664b43909200c5ed5e6fa2
Title: Apple Watch Ultra 2
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Watch(props) {
  const { nodes, materials } = useGLTF('/watch.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.70}>
        <mesh geometry={nodes.NONHYSHLUQzoyez.geometry} material={materials.JSFaTttTQosHtdR} />
        <mesh geometry={nodes.nUikKFsvZdptvXF.geometry} material={materials.edhWAPEBZsqCLTg} />
        <mesh geometry={nodes.VHnHbLOyhEXLvWA.geometry} material={materials.edYkGGAdRWeopLP} />
        <mesh geometry={nodes.DCiPNWQGULbWNNE.geometry} material={materials.AGtKlWnOInmqNQI} />
        <mesh geometry={nodes.LbodUHJUCGqowCz.geometry} material={materials.PmrTDgoSkxCPUel} />
        <mesh geometry={nodes.BMKlRAQYzgiNCrq_1.geometry} material={materials.yKAKXxwHUkGVYpC} />
        <mesh geometry={nodes.joGEgikMuDmcVlT.geometry} material={materials.GXPSJdzybTrBefY} />
        <mesh geometry={nodes.ytGVVkppetlPrjk.geometry} material={materials.CdZJpyOXLDMygZg} />
        <mesh geometry={nodes.bXoKVYbQhcORrRo.geometry} material={materials.AGtKlWnOInmqNQI} />
        <mesh geometry={nodes.LMTUXYhSYYJrnsy_0.geometry} material={materials.LMTUXYhSYYJrnsy_0} />
        <mesh geometry={nodes.HoKUOQkmlXGGrun.geometry} material={materials.YtajTVWccmKRZBL} />
        <mesh geometry={nodes.LMTUXYhSYYJrnsy.geometry} material={materials.edhWAPEBZsqCLTg} />
        <mesh geometry={nodes.niuesVpLyOylhzG.geometry} material={materials.edhWAPEBZsqCLTg} />
        <mesh geometry={nodes.dAobUVRiwHRHUwW.geometry} material={materials.GvXrALMIeaGmIJo} />
        <mesh geometry={nodes.odYscQETIRVJKxR.geometry} material={materials.KjETpDnldvdbNBw} />
        <mesh geometry={nodes.qHpopFXBXmHOUYS.geometry} material={materials.VJcIxaYCeMHzzAJ} />
        <mesh geometry={nodes.AXTiAWNANGWNPZh.geometry} material={materials.vqobCvtAVyNLbeh} />
        <mesh geometry={nodes.pYoTjWyHwknCsXs.geometry} material={materials.edhWAPEBZsqCLTg} />
        <mesh geometry={nodes.GYKIDhUtSmfksAh.geometry} material={materials.edhWAPEBZsqCLTg} />
        <mesh geometry={nodes.tZSTMNOYIPNFEiO.geometry} material={materials.YtajTVWccmKRZBL} />
        <mesh geometry={nodes.IIYcDhGuQelMSoT.geometry} material={materials.JlRKetQcktLwJwa} />
        <mesh geometry={nodes.jGEqmDFMbHJGHIM.geometry} material={materials.NfRpqTxrWQxoAIy} />
        <mesh geometry={nodes.EefvmwIVeXQqJgK.geometry} material={materials.gYvxxOpBYwEcvOZ} />
        <mesh geometry={nodes.pPJyCszCvDGrLse.geometry} material={materials.edhWAPEBZsqCLTg} />
        <mesh geometry={nodes.gkDXZCmXAkhmUzR.geometry} material={materials.gYvxxOpBYwEcvOZ} />
        <mesh geometry={nodes.UNygooOJQBdvEQH.geometry} material={materials.ihcWbztBiuXfzKC} />
        <mesh geometry={nodes.URfXVlSvtJbSCOD.geometry} material={materials.EbFYvXZFEOELnji} />
        <mesh geometry={nodes.OFYufNMwvtHmxdH.geometry} material={materials.hSvQcziHKpXubDY} />
        <mesh geometry={nodes.mcBIQkSNmBqhwzR.geometry} material={materials.CdZJpyOXLDMygZg} />
        <mesh geometry={nodes.dEKwzvajmGpjRpl.geometry} material={materials.yXTwmSCvToGuMDP} />
        <mesh geometry={nodes.iQrteZnlrWZpbxz.geometry} material={materials.VkUcBAhoopQFcky} />
        <mesh geometry={nodes.ggBokQJJgYcckom.geometry} material={materials.IvaXKlaVZetAvuj} />
        <mesh geometry={nodes.SWRxiioprGlZKOq.geometry} material={materials.dSEglLtoqwjlQIP} />
        <mesh geometry={nodes.AnKriXdRdkHvVgp.geometry} material={materials.IsuszdatyklnjoT} />
        <mesh geometry={nodes.nKBIvEakrYhfdsQ.geometry} material={materials.ICUREbcRKnCadKa} />
        <mesh geometry={nodes.VqmyRLxQuilpALX.geometry} material={materials.CevCCqOWPSfMvyq} />
        <mesh geometry={nodes.IYFwQnCDaiSiRdc.geometry} material={materials.AGtKlWnOInmqNQI} />
        <mesh geometry={nodes.FiiGAhWFHdUxhDn.geometry} material={materials.boERCOkfaeYKPmb} />
        <mesh geometry={nodes.pVqLnJdxODmWtTg.geometry} material={materials.troyYZUIqRYbiDX} />
        <mesh geometry={nodes.vyDTdhAtbzsQFUf.geometry} material={materials.ivgxAOQoWknkmNj} />
        <mesh geometry={nodes.fOvUJMAYMqVGOTV.geometry} material={materials.FsJfKVbzNLXJeBa} />
        <mesh geometry={nodes.ffjHNJzYIjDziJe.geometry} material={materials.sTxeXXVKohXeDJU} />
        <mesh geometry={nodes.dGxaGtgSeaFVukl.geometry} material={materials.sTxeXXVKohXeDJU} />
        <mesh geometry={nodes.YXUXfLDEwbvOPVY.geometry} material={materials.sTxeXXVKohXeDJU} />
        <mesh geometry={nodes.jLHIkNOojYqBogV.geometry} material={materials.sTxeXXVKohXeDJU} />
        <mesh geometry={nodes.OmcQxRYSzLYYjzi.geometry} material={materials.sTxeXXVKohXeDJU} />
        <mesh geometry={nodes.HGmbyGfKBcsbZXU.geometry} material={materials.sTxeXXVKohXeDJU} />
        <mesh geometry={nodes.EZmdWXCjqrUDeoX.geometry} material={materials.lgIBGhMXHpTEcfq} />
        <mesh geometry={nodes.KUPfCqZVKycFVaN.geometry} material={materials.lgIBGhMXHpTEcfq} />
        <mesh geometry={nodes.PiDhoxwwGLYiaUX_0.geometry} material={materials.sTxeXXVKohXeDJU} />
        <mesh geometry={nodes.RJSoCQhkGkkzpXt_0.geometry} material={materials.sTxeXXVKohXeDJU} />
        <mesh geometry={nodes.YufihILXVHVrDwt.geometry} material={materials.lgIBGhMXHpTEcfq} />
        <mesh geometry={nodes.kAITCUcjTiAaCrp.geometry} material={materials.lgIBGhMXHpTEcfq} />
        <mesh geometry={nodes.wKIPMqpyTsCHWIy.geometry} material={materials.edhWAPEBZsqCLTg} />
        <mesh geometry={nodes.AGCoudWoaDmiMRH.geometry} material={materials.edhWAPEBZsqCLTg} />
      </group>
    </group>
  )
}

useGLTF.preload('/watch.gltf')
